# Generated by Django 5.0.6 on 2024-05-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
    ]
